require File.dirname(__FILE__) + "/model/image_repository"
require File.dirname(__FILE__) + "/model/note_repository"
require File.dirname(__FILE__) + "/model/image"
require File.dirname(__FILE__) + "/model/punctuation"
require File.dirname(__FILE__) + "/model/composer"
require File.dirname(__FILE__) + "/model/element"