require File.dirname(__FILE__) + "/model/images"
require File.dirname(__FILE__) + "/model/notes"
require File.dirname(__FILE__) + "/model/image"
require File.dirname(__FILE__) + "/model/punctuation"
require File.dirname(__FILE__) + "/model/composer"
require File.dirname(__FILE__) + "/model/element"